CREATE DATABASE IF NOT EXISTS db;
USE db;

CREATE TABLE IF NOT EXISTS tasks(
    id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT
);
ALTER TABLE tasks
    ADD IF NOT EXISTS task TEXT NOT NULL,
    ADD IF NOT EXISTS description TEXT NOT NULL;
